# Numpy <hr style="border:2.5px solid rgba(190, 11, 200, 1) "></hr>

<b>REINALD DERIC E. AMAR</b>
<br>COMPUTER ENGINEER

In [1]:
# imports and packages
import numpy as np

# 1D Array

In [2]:
my_array = np.array ([1,2,3])

In [3]:
type(my_array)

numpy.ndarray

In [4]:
np.shape(my_array)

(3,)

# 2D Array


In [5]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.shape(my_array)

(2, 3)

In [7]:
trans_array = my_array.T

In [8]:
trans_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [9]:
np.shape(trans_array)

(3, 2)

In [10]:
np.sum(trans_array,axis=0)

array([ 6, 15])

In [11]:
np.sum(trans_array,axis=1)

array([5, 7, 9])

# Measure of Central Tendency


In [12]:
resistance = np.array([
    [10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8], # Jaguar
    [10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1,np.nan], # Panther
])

In [13]:
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [ ]:
# Mean
np.nanmean(resistance, axis=1)ym

SyntaxError: invalid syntax (3248011601.py, line 2)

In [ ]:
# Range
res_max = np.nanmax(resistance, axis=1)
res_min = np.nanmin(resistance, axis=1)

res_range = res_max - res_min
res_range

array([ 8. , 10.9])

In [16]:
print(f'Jaguar_range = {res_range[0]:.2f} ohms')
print(f'Panther_range = {res_range[1]:.2f} ohms')

Jaguar_range = 8.00 ohms
Panther_range = 10.90 ohms


In [17]:
# 1st Quartile
res_Q1 = np.nanpercentile(resistance, 25, axis=1)
res_Q1

array([9.4  , 9.125])

In [18]:
# 2nd Quartile
res_Q2 = np.nanpercentile(resistance, 50, axis=1)
res_Q2


array([9.8 , 9.55])

In [19]:
# 3rd Quartile
res_Q3 = np.nanpercentile(resistance, 75, axis=1)
res_Q3


array([10.45 , 10.625])

In [20]:
# IQR
print(f'Jaguar IQR = {res_Q3[0] - res_Q1[0]:.2f} ohms')
print(f'Panther IQR = {res_Q3[1] - res_Q1[1]:.2f} ohms')


Jaguar IQR = 1.05 ohms
Panther IQR = 1.50 ohms


In [21]:
# Variance
res_var = np.nanvar(resistance, ddof=1, axis=1)
res_var


array([ 4.86      , 11.08277778])

In [22]:
print(f'Jaguar Variance = {res_var[0]:.2f} ohms')
print(f'Panther Variance = {res_var[1]:.2f} ohms')


Jaguar Variance = 4.86 ohms
Panther Variance = 11.08 ohms
